### ISSUE TITLE
unable to use the trained model of SigCom-LINCS if there is no gene list data

### ISSUE THREAD

**Issue by jmche** [MaayanLab/L1000toRNAseq#2]
I download the "LINCS L1000 CycleGAN models" from the https://maayanlab.cloud/sigcom-lincs/#/Download.

However, It's really hard to use the model since there isn't any data information. Would you provide some data information?
I matched 977 genes using "GSE92742_Broad_LINCS_gene_info.txt" and "GSE92742_Broad_LINCS_gene_info_delta_landmark.txt" from GSE92742. However, the trained step1 model needs 962 genes and I couldn't know which 962 genes were used.

I would appreciate it if you could provide the test data and gene list(962 L1000 genes & predicted 23614 RNA-seq genes(the gene list order is the same with "Computed Signatures for CycleGAN Predicted RNA-Seq-Like Profiles of L1000 Samples")) of the trained model.

**Comment by sherxie** [comment]
Hi @jmche, thank you for the question. We will include the gene information in the models file in the future, but for now you should be able to download the gene information from [this link](https://lincs-dcic.s3.amazonaws.com/LINCS-L1000-Transformed/L1000_to_RNAseq_GeneInfo.zip). The `overlap_landmark_gene_file.txt` and `overlap_rnaseq_gene_file.txt` should contain the 962 L1000 genes and 23614 RNA-seq genes that you asked for, respectively.
